version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 099199746132.dkr.ecr.eu-west-1.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t demo-project-ecr-0001 .
  post_build:
    commands:
      - echo After the build completes, tag your image so you can push the image to this repository...
      - docker tag demo-project-ecr-0001:latest 099199746132.dkr.ecr.eu-west-1.amazonaws.com/demo-project-ecr-0001:latest
      - echo Pushing the Docker image...
      - docker push 099199746132.dkr.ecr.eu-west-1.amazonaws.com/demo-project-ecr-0001:latest
  
