version: 0.2

env:
  variables:
    AWS_ACCOUNT_ID: "099199746132"
    AWS_DEFAULT_REGION: "eu-west-1"
    REPOSITORY_URI: "099199746132.dkr.ecr.eu-west-1.amazonaws.com/node-app-image-repository"
    IMAGE_TAG: "latest"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      #- IMAGE_TAG="$(date +%Y-%m-%d.%H.%M.%S)-$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-8)"
      

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - echo Docker image built successfully.

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Docker image pushed successfully.
      - echo Writing image definitions file...
      #- printf '[{"name":"my-container","imageUri":"%s:%s"}]' $REPOSITORY_URI $IMAGE_TAG > imagedefinitions.json
      - printf '[{"name":"nodejs-backend-container","imageUri":"%s:%s"}]' $REPOSITORY_URI $IMAGE_TAG > imagedefinitions.json
      
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
