version: 0.2

env:
  variables:
    AWS_ACCOUNT_ID: "099199746132"
    AWS_DEFAULT_REGION: "eu-west-1"
    REPOSITORY_URI: "099199746132.dkr.ecr.eu-west-1.amazonaws.com/node-backend-ecr-repository"
    IMAGE_TAG: "latest"

phases:
  pre_build:
    commands:
      
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      
      

  build:
    commands:
      
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      

  post_build:
    commands:
      
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      
     
      - printf '[{"name":"nodejs-backend-container","imageUri":"'$REPOSITORY_URI:$IMAGE_TAG'"}]' $REPOSITORY_URI $IMAGE_TAG > imagedefinitions.json
      
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
